title: while True
email: b52H389@gmail.com
description: >-
  Sharing tools, ideas and investigations on software.
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kersanszki-levente.github.io"
github_username: kersanszki-levente

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
